### ISSUE TITLE
Should the documentation on parent child communication mention watchers

### ISSUE THREAD

**Issue by aldencolerain** [vuejs/vuejs.org#1005]
I've seen quite a few questions regarding the correct way to call a function on a child component from a parent.  I assume that most of the time with one way data binding the ideal way to do this is when a prop changes the child should use a watcher or (as mentioned in the docs) a computed value.  If setting a watcher is the "correct" way to call a function in response to something happening on the parent it might be worth a one liner in that section of the docs.  Either way it might be worth fleshing out that section just a tiny bit more?

**Comment by chrisvfritz** [comment]
Hmm, that's not really parent-child communication though. That's communication _within_ a component. The component has access to some data (which just happens to be from a prop) and watchers make something happen, depending on the changing state of that data, exactly as demonstrated earlier in the guide.

In a lot of the cases where I see people ask the question with that specific frame:

> the correct way to call a function on a child component from a parent

If you're thinking of it as the _parent_ doing the calling, then the function is probably really in the parent's domain and doesn't actually belong in the child. In these cases, the function is usually only written in the child because it already had access to all the data it needed (its own, plus the parent's via props). In these cases, events sent up from the child are usually the right answer. Or in more complex cases, neither parent nor child should really own the data or functions - and that's where more robust state management like Vuex comes in.

Does that make sense? If I've misunderstood, please feel free to link to the specific use cases and questions you're referring to.

**Comment by chrisvfritz** [comment]
Haven't gotten an answer on this, so I'll assume the the question is resolved for now.

**Comment by aldencolerain** [comment]
@chrisvfritz

Sorry about the late reply. Perhaps I framed it incorrectly but often I hear a lot of discussion about this. I understand what your saying about watchers being internal component communication and that totally makes sense to me but often people have the question how do I make a child component react to a changes in a parents state. I think the answer is a prop and a watcher and to me that is a question most new people think of as parent child communication. The docs are super clear on computed derivations of props/parent state changes but vague when those reactions to parent data are not simply data trasformations. I can understand if you want to keep the issue closed but this is definitely a sticking point I hear a lot with people new to Vue. I think there's a little gap in the docs perhaps because solutions to the problem are obvious from experts in the Vue paradigm. Thoughts?

**Comment by chrisvfritz** [comment]
@aldencolerain Which part do you think people are missing? The idea that they can pass data to a child component with props, or that they can watch data with watchers? If you could provide an example use case, it could be helpful.
