### ISSUE TITLE
Improve documentation example

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vuejs/vuejs.org#1028]
https://vue-style-guide-dev.surge.sh/v2/guide/style-guide.html#Self-closing-components

The example here is bad. The documentation should **tell**; the example should **show**. But it doesn't **show** an example *in context*. It **tells** you the context (via comment), but doesn't explain *through example* how these should be used properly.

The examples should be updated to actually show the code **in** a single-file component, string template, and DOM template. Or at the very least link to examples of what each of those actually **look** like. To someone new you are using undefined jargon. **Show**, don't tell.

**Comment by chrisvfritz** [comment]
If someone is new to Vue, they'll need to learn how to use it at all before learning to use it better in the style guide. Style guides always assume a level of familiarity. Either way though, this style guide is still being developed internally and isn't yet ready for public feedback. We'll provide an announcement when it is. 🙂

**Comment by TheJaredWilcurt** [comment]
@chrisvfritz That's cool, I didn't realize it was still under development (should have looked at the URL).

Though I have to say I disagree with your approach.

From my experience, style guides are most commonly used in workplaces as a document to point to for justification when requesting a change in a pull request. "Change this section to this, because [link]". Those most in need of this explanation, logically, will be those newest to Vue.js and not familiar with all it's internal jargon. So showing an **in-context** example is the best way to prevent any confusion, misunderstanding, or misinterpretation. It's also the easiest way to educate people on the platform and its best practices as there is a clear and unambiguous example.

Also, you're already doing this elsewhere in the page, like in these places:

* https://vue-style-guide-dev.surge.sh/v2/guide/style-guide.html#Component-data
* https://vue-style-guide-dev.surge.sh/v2/guide/style-guide.html#Component-style-scoping

If putting full context for the example would make it too long or could lead to it being complex to the point where it's not aiding in the understanding of the concept, then you should be linking to definitions/documentation of the jargon used, so examples of those separate concepts can be seen there.

**Comment by gustojs** [comment]
I'm using Vue since Vue 1 and I still miss some examples or explanation to fully understand some points, but I'll wait with specific feedback until you say it's OK now.

**Comment by chrisvfritz** [comment]
@TheJaredWilcurt @gustojs I'll definitely be doing more linking in the final version - just mostly holding off on the initial pass to avoid breaking up my flow of thought as I write. I think I've also found a way to represent in-DOM templates in a way that doesn't make the examples too long, so I'll be updating the examples mentioned as well.

By the way @TheJaredWilcurt, I regret being so dismissive in my comment back to you. When reading issues, I try to look past how and what people are saying to the feeling/situation behind it, but at 3am when I wrote that my capacity was lower, so I failed. 😕  I can tell you had very good intentions when opening the issue and I do appreciate the community helping us to smooth out rough edges in the docs.

Because I know you have good intentions, I want to let you know that the way the issue was written was very off-putting to me. First, reading "The example here is bad" just put me on the defensive. It's like if someone put a lot of work into making you a meal and your first feedback is just, "This food is bad." It can often sound arrogant and dismissive - like you're the mean judge on a reality show. 😄 

Then you go on to explain a general principle we should be following in our docs with "show, don't tell", assuming we haven't heard of this simple axiom. The repetition and bolding came across to me as very aggressive and condescending. It also seemed hypocritical to me, since the issue itself didn't follow its own advice, never showing examples of what you'd like to see.

Here's an example of how the issue could be rewritten in a way that would have been more helpful and better received:

> In the style guide, I think the examples [in Self-closing components](https://vue-style-guide-dev.surge.sh/v2/guide/style-guide.html#Self-closing-components) could use more context to help people who are less familiar with single-file components, string templates, or JSX. For example, I really liked the context provided to explain when component data should be a function:
>
> ``` js
> Vue.component('some-comp', {
>   data: {
>     foo: 'bar'
>   }
> })
> ```
>
> This is more intuitive to me than a comment to provide context would have been, such as:
>
> ``` js
> // In a component
> data: {
>   foo: 'bar'
> }
> ```
>
> Would it work to use the same strategy in these examples? Or, if it would make the examples too long in this case, what about links to examples in the initial description?

Some notable differences in that version:

- Vague, absolute language is avoided (e.g. "X is bad")
- The tone acknowledges subjectivity (e.g. "I think", "to me")
- Questions are asked, instead of making demands (e.g. "Would it work", "what about" instead of "should be updated",  "at the very least")

I hope that helps! 🙂  When the style guide is ready for public review, I'll update #875.

**Comment by kospl** [comment]
Hey, guys. I don't know if I should open another issue, but documentation and examples for https://vuejs.org/v2/style-guide/#Self-closing-components-strongly-recommended are still kind of misleading, and maybe can be named as being not correct at all:

![image](https://user-images.githubusercontent.com/26386660/104956641-38c0d600-59d5-11eb-9416-a416b29a5a21.png)
![image](https://user-images.githubusercontent.com/26386660/104956652-40807a80-59d5-11eb-8d4e-33d5ff68c768.png)

Let me explain here, so documentation says **self-closing** tags should NOT be used ONLY for DOM templates:  `but never in DOM templates`. Which is not true - because _string templates_ also CANNOT be used by self-closing tag.

Here is example which shows that self-closing tag for string templates is not usable: https://codepen.io/sheriffderek/pen/rQGLve (from https://github.com/vuejs/vue/issues/1036#issuecomment-439716534)

Then the following example showed as **bad**:

```
Bad
<!-- In single-file components, string templates, and JSX -->
<MyComponent></MyComponent>
```
Which is not true - it's working perfectly for _string templates_.

I tested provided codepen example with latest Vue `2.6.12`. 

Let me know if you can fix this ASAP, as developers are struggling to get actual help from documentation for a good 5 years: https://github.com/vuejs/vue/issues/1036#issuecomment-171985266
