### ISSUE TITLE
Add maquette.js to comparisons guide

### ISSUE THREAD

**Issue by zcyzcy88** [vuejs/vuejs.org#1034]
Looks really simple.

**Comment by chrisvfritz** [comment]
I'm open to this if Maquette grows a larger user base, but as of writing, it has less than 1000 downloads from NPM in the entire last month. It's not a judgment on the quality of the library, but since it requires a lot of work to keep this page up to date, I'd like to avoid comparisons that won't be useful to a significantly large group of people. I hope you understand! 🙂

**Comment by chrisvfritz** [comment]
Even though it won't be added to the comparisons page, I've just taken a look at Maquette and it's currently simple enough that I'm happy to provide a very short (though possibly flawed) comparison. Here are some differences:

- Ecosystem and support. With younger projects with small communities like Maquette, you don't know if it'll continue to be supported. If you want to use it, it may eventually fall to you to fix bugs, develop features, and write companion libraries to extend it for common use cases.
- API size. Maquette has a much smaller API. This makes it faster to learn Maquette's API - though it'll take more time to learn how to work around its issues, since there'll be fewer existing Stack Overflow questions and blog posts. With that factored in, I'd actually argue that with Vue's docs and community, it'll be faster to learn to build the same applications in Vue.
- File size. At 3KB against Vue's 20KB (or 29KB if not using the runtime-only build). But since Maquette does much less for you (by design), it generally takes more user code to do the same things. In non-trivial apps, this could soon cancel out the size advantage Maquette has.
- Robustness. Another cost of the small file size is lots of edge cases you'll spend more time working around. For example, while event handlers trigger an update in Maquette, not all state updates do (e.g. a counter that updates every second with `setInterval` will not trigger a rerender). With more code in Vue, you get a reliable reactivity system. You update the state (anywhere and at any time) and the view efficiently re-renders what it needs to, based on what changed.
- Organization. Vue's components offer an encapsulated and consistent organization, while Maquette allows users to organize components however they'd like, so they'd have to essentially invent their own API for the library in medium-sized applications and larger.
- Scale. Vue scales up as well as it scales down. It's clear that Maquette is marketing itself as a utility library, so it's not even trying to be suitable to manage your views on its own in non-trivial applications.

Personally, I very rarely work on a project where Vue's already tiny 20KB is prohibitive. When I do, I can only afford to write a small amount of JS anyway, so the use case is always simple enough that I can do what I want with plain JS - no libraries. Maquette adds so little convenience that I don't think it's even worth 3KB in those cases. I wonder if it's targeting a niche that doesn't exist. 😕
