### ISSUE TITLE
Explanation of build types

### ISSUE THREAD

**Issue by RIanDeLaCruz** [vuejs/vuejs.org#1055]
Hi.

I noticed that all examples in the explanation of the build types found [here](https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only) do not talk about using Single File Components.

Maybe it can be incorporated in, somehow? This issue seems to come up when it comes to adding external components (those created by the community). Errors like `vue: failed to mount component: template or render function not defined` come up because importing them needs some other workaround.

**Comment by RIanDeLaCruz** [comment]
@chrisvfritz When I'm trying to import community libraries, I've had to do what was mentioned here:
https://github.com/matfish2/vue-tables-2/issues/185. It was mentioned by user afuno.

And, to make it more explicit, I've created [this gist](https://gist.github.com/RIanDeLaCruz/684f2f88216486fa991971a5f0bcf0b7)

**Comment by chrisvfritz** [comment]
This is something for each community library to document, since we won't know how they're compiling and exposing their project. If they require use of the the full standalone build, I'd say they're doing it wrong. 

In fact, we don't recommend code like:

``` js
import Vue from 'vue/dist/vue.esm.js'
```

As it can lead to a different version of Vue being used by other libraries, such as `vue-loader`. Instead, the section you linked to provides examples of how to alias `vue` to the specific build you need with various build systems. 

As a sidenote, I don't recommend `Vue.use` inside a component file, but rather before you initialize your root Vue instance, where you're already importing Vue.

**Comment by RIanDeLaCruz** [comment]
So, if I understand this correctly, using full builds for community libraries is discouraged

But, if that is the case, the use of the full build should be done in the build system, instead of importing?

**Comment by chrisvfritz** [comment]
Exactly!
