### ISSUE TITLE
A commit that changes the way Vue.delete works shouldn't be titled as a typo

### ISSUE THREAD

**Issue by OmerZfira** [vuejs/vuejs.org#1059]
Is it possible to make this change more obvious for anyone like me who is looking in the docs for when the behaviour of Vue.delete changed?
commit hash:  bffedab6d824cc7983856b6f286e69f0d818c3a7

Thanks

**Comment by chrisvfritz** [comment]
The `with on Array` was the typo. I might be misunderstanding, but it started working with arrays in v2.2.0+, as stated in the section you referenced. If you just mean, "How can I review changes to Vue between versions?", then I recommend the [Releases page](https://github.com/vuejs/vue/releases) on GitHub.

Does this help? Am I correctly understanding what you're asking?

**Comment by LinusBorg** [comment]
@chrisvfritz I think he saw that you "added" the line: 

`Only works with Array + index in 2.2.0+.`

...but he missed that you also removed this line:

`> Also works with on Array + index in 2.2.0+.`

Essentially just moving and re-wording the sentence. Because he missed this, it made it seem like your new sentence introduced a new behaviour to the docs with a commit labeled "fix typo".

**Comment by OmerZfira** [comment]
@LinusBorg Yes, that was it, thanks for the clarification.
This can be closed.

**Comment by chrisvfritz** [comment]
Thanks to both of you! I like `Only in 2.2.0+: Also works with Array + index.` much better and have just updated. 🙂
