### ISSUE TITLE
Split `components.md` into a full section ?

### ISSUE THREAD

**Issue by Haeresis** [vuejs/vuejs.org#1220]
The Essential part of Vue guide is really simple and quick to read. It introduces all mechanisms about Vue in the most simple usage, i. e. just use it like any others JavaScript tool on a specific part of code. So, without component aspect, Vue is still a great tool you can just use, why not, with multiple `new Vue` on multiple part of a DOM.

To me, the component level is the second part of comprehension of tool for a beginner. And it's a complete part. It's why `components.md` is a soooo long file to read.

It's why, it should not be a big deal to explode the content of `components.md` into multiple file exposing each concepts of component, `Using Components`, `Props`, `Custom Events` etc. under a complete section (same as Essential, Transitions & Animation, etc.).

What your throughs about that ? And without complete new section, what your throughts about split this really loooong file ?

**Comment by chrisvfritz** [comment]
Hmm, I do want to keep components under Essentials, because I think it really is important for anyone using Vue to understand. I agree that it's very long though, so I'm open to splitting it into multiple pages and reorganizing. There are also cases where we can provide a briefer explanation, then link to the style guide for more info (e.g. `data` Must Be a Function).

As a first effort, I'll try to make a pass soon to revise and reorganize. During that process, I may also see some sections that could really be pulled out into a separate page outside of Essentials.

**Comment by Haeresis** [comment]
I would just know if you have already thinking about the fact of components.md is too long ;)
