### ISSUE TITLE
<a> element margin-collapse

### ISSUE THREAD

**Issue by baixiaoyu2997** [vuejs/vuejs.org#1249]
<a> element margin-collapse(sorry for my english)

**Comment by Justineo** [comment]
Hi, can you describe the issue more clearly?

**Comment by baixiaoyu2997** [comment]
ok ,see this img:
![](http://wx1.sinaimg.cn/large/59ab4c9fly1fl5vtmq7s4j20yg0grjuc.jpg)

i think margin  did not achieve the desired effect，this is a wrong click area

**Comment by Justineo** [comment]
As I understand, the top margin is by design, by applying a `::before` pseudo element to `<h2>`, probably to keep the heading away from the top nav. But I think the generated DOM structure is not correct (there's an `<a>` inside another `<a>`). Maybe it should be something like:

```html
<h2 id="Cimposing-with-Components">
  <a href="#Cimposing-with-Components" data-scroll>Composing with Components</a>
</h2>
```

**Comment by Jinjiang** [comment]
The problem seems caused by:
https://github.com/vuejs/vuejs.org/blob/3b3b9b50e8dbdc3404bea5452c0bb7cd424b359e/themes/vue/source/css/page.styl#L57
and
https://github.com/vuejs/vuejs.org/blob/3b3b9b50e8dbdc3404bea5452c0bb7cd424b359e/themes/vue/source/css/page.styl#L222

I found that if the value isn't very small (greater than approximately `20px`), it won't affect the space above headings. But the greater it is, the more it will cover the content above.
So I reduced the value.
At the same time I used a little trick to remove the inner `<a>` which is generated from markdown parser.
See: #1253
