### ISSUE TITLE
Styleguide: File naming convention with casing

### ISSUE THREAD

**Issue by carsongee** [vuejs/vuejs.org#1261]
The style guide continually uses examples of CamelCase file names such as `TodoList.vue` throughout the document, even though it notes the problem of case insensitive file systems in the section on component file name casing.  

I would suggest that the least problematic file naming convention of using kebab case should be the default used throughout the document to reduce potential issues with applications that developed with multiple developer OS teams.

If you agree, I'd be happy to follow up with a PR to make the changes.

**Comment by chrisvfritz** [comment]
PascalCase is the primary recommendation because it's what the majority of the Vue team uses, it works better with autocompletion in text editors, and is generally the most popular convention among other component-based frameworks. (I know Angular 2 is an exception, preferring kebab-case).

I actually agree with you personally and prefer kebab-case filenames in my projects for this reason, but I've also used PascalCase very successfully in teams that include every major OS. The main issue is renaming a file with only case changes (e.g. `Todoitem` -> `TodoItem`), which is admittedly rare and there are known workarounds.

There are compelling reasons to use either convention, which is why both are acceptable in the Style Guide. If we switched everything to kebab-case, we'd unfortunately just get another issue opened to switch everything to PascalCase. No matter what, we won't make everyone happy. 😅

Does that make sense?

**Comment by carsongee** [comment]
Having been the DevOps guy who always has to fix the inevitable `(e.g. Todoitem -> TodoItem)` I'm more sensitive to it, as its cost me a lot of productivity over the years, which is why I filed the issue. 

Say we did change it to kebab in the doc, and we did get an issue complaining like I have here 😜. I'd reply with  the reasoning that the guide is general recommendation and we chose the convention that reduces the likelihood of encountering a known and tricky to diagnose developer productivity issue with git/OS filesystem case sensitivity disagreements.

All that said, I understand it is mostly an "emacs vs vi" decision, so no sweat if you want to keep going as is.  At least the next guy like me can see this issue.
