### ISSUE TITLE
component event fired twice

### ISSUE THREAD

**Issue by cheungkonghou** [vuejs/vuejs.org#1278]
Hi,

On the example https://vuejs.org/v2/examples/select2.html, I added a v-on:input event on the component and is fired twice. How to fix this?
https://jsfiddle.net/d131Lebj/127/

Cheung

**Comment by chrisvfritz** [comment]
Unfortunately, since we have limited time, we have to reserve issues for feature requests and bugs. For usage questions like this, I recommend posting to either [the forum](http://forum.vuejs.org/) or [the chat](https://chat.vuejs.org/). Both include great communities of users that should be able to help.

**Comment by cheungkonghou** [comment]
Isn't it a bug? Event shouldn't be fired twice.

**Comment by chrisvfritz** [comment]
Ah, I see what you mean - I misread your comment. I just updated the example so it should no longer be happening. 🙂
