### ISSUE TITLE
Form validation demo

### ISSUE THREAD

**Issue by cfjedimaster** [vuejs/vuejs.org#1314]
I'd like to create a Cookbook entry that demonstrates form validation with Vue. This would be based heavily on the blog post I did here: https://www.raymondcamden.com/2017/12/07/an-example-of-form-validation-with-vuejs/

**Comment by sdras** [comment]
Hi Raymond! This seems like a really great entry for the cookbook. The only thing I might add would be a mention of vuelidate as an alternative pattern, as it's usage is fairly ubiquitous in Vue. What do you think @chrisvfritz?

**Comment by chrisvfritz** [comment]
@sdras @cfjedimaster I like the topic! vee-validate is another popular library I think we should mention as an alternative, but I agree focusing on building form validations from scratch is the right focus. It'll probably be the most educational and also easier to keep up-to-date. 😄

**Comment by cfjedimaster** [comment]
What is the next step? I assume my blog entry can't be used as is - that first paragraph would need to change. But how should I get a draft to yall?

**Comment by sdras** [comment]
As I mentioned previously on twitter, please use [this template](https://vuejs.org/v2/cookbook/cookbook-contributions.html) as a guide. you can look at "adding instance properties" as an example as well. You'd submit a PR here and we'd review it. You'd probably have to rewrite the post to fit our format, but there's a lot of content there that's reusable with some eye to formatting. Thanks

**Comment by cfjedimaster** [comment]
Ah sorry - forgot that earlier tweet. Doing too much at once. :) Thank you for the reminder.

**Comment by sdras** [comment]
No worries! Thanks

**Comment by cfjedimaster** [comment]
Are codepen's ok? I love that users can see the code and run it directly on the page, but having it tied to my account may not be safe.

**Comment by sdras** [comment]
I like codepens. We've also used JSFiddle and CodeSandbox, it's probably no less safe than those- I know codepen does a lot of security work.

**Comment by cfjedimaster** [comment]
I guess my issue is - are you (the official Vue you ;) ok with "my" codepens being on the site? I don't mind for sure, but wanted to make sure that was ok.

**Comment by sdras** [comment]
I'm not sure why you think the answer is any different? We're using CodePens for the cookbook.

**Comment by cfjedimaster** [comment]
Sorry - I guess I was just worried about there being a "policy" against using someone's pen (even the author of the entry) on vuejs.org. I'm over thinking it - I'll just go for it.

**Comment by sdras** [comment]
If at any point we move over to using an official Vue account I will let you know and move it over. For now, it's fine, unless you don't feel comfortable, in which case I can move it over when you submit your PR.

**Comment by chrisvfritz** [comment]
Just hopping in to provide some clarification on this. 🙂 In the past, I've preferred that embedded and linked examples are under an account of a core team member, for these reasons:

- Users could potentially update their pens/fiddles/etc so that they no longer match our content (either accidentally, or on purpose to make the example more impressive, but also more complex than we'd like).
- Authors of embedded examples could essentially vandalize Vue's website if they wanted to, or use it to bring attention to a political statement.
- When an example has to update, it's easier to update inline (rather than creating a fork) when one of us already controls the example. This way, when people copy the links and post them elsewhere in the community, they remain up-to-date.

@sdras Let me know what you think. If you feel that kind of policy won't make sense for the cookbook, I'm definitely open to reconsidering it!

**Comment by sdras** [comment]
I think that makes sense. I'll kick off a Vue codepen account (they have team accounts that you can invite multiple people to), that probably will be the most cohesive approach. @cfjedimaster I'll port your examples over after we finish the PR review. Thanks everyone!

**Comment by sdras** [comment]
Alright, I've made a team codepen account, I'll move all of the examples that come in over there: https://codepen.io/team/Vue/

**Comment by sdras** [comment]
completed!
