### ISSUE TITLE
Mismatched anchor links in API page

### ISSUE THREAD

**Issue by kaungmyatlwin** [vuejs/vuejs.org#1352]
In API page, some of the sidebar links are broken and will not scroll to anchor.

For example,

`https://vuejs.org/v2/api/#vm-mount-elementOrSelector` is in the sidebar link whilst the actual anchor link should be `https://vuejs.org/v2/api/#vm-mount` in order to scroll to desired position.

Also several sidebar links are broken too. As far as I know it's only in API page.

Is this intended behavior? I'll report more links if these are bugs.

**Comment by matiaslauriti** [comment]
I also found that any **Global API** sub item is broken too.

For example `Vue.Extend` will try to go to `#vue-extend-options` but the anchor in the [docs](https://github.com/vuejs/vuejs.org/blob/master/src/v2/api/index.md) is `#vue-extend`.

**Comment by gustojs** [comment]
There are two ways to deal with this issue. Both have good and bad sides.

1) Remove all the `(arguments)` part of each subtitle, because that's what messes up the anchor links. This will require a small redesign of API (putting arguments elsewhere), because we definitely don't want to lose such data.
2) Creating menu with implicit list of links to each section. This of course will make the website more difficult to maintain in the longer run.

That's why while we can fix it ourselves, the decision has to made by core team members.

**Comment by rekateka** [comment]
I believe this has been fixed and deployed. See https://github.com/vuejs/vuejs.org/pull/1348.

**Comment by chrisvfritz** [comment]
Yep, w should be good!
