### ISSUE TITLE
Components #Compilation Scope example is not replicable?

### ISSUE THREAD

**Issue by Hacktivista** [vuejs/vuejs.org#1465]
I had a bad time trying to replicate the example on [v2/guide/components.html#Compilation-Scope](https://vuejs.org/v2/guide/components.html#Compilation-Scope)

> Imagine a template like this:
> 
> ```
> <child-component>
>   {{ message }}
> </child-component>
> ```
> 
> Should the message be bound to the parent’s data or the child data? The answer is the parent.

As explicitly mentioned on the [next subsection](https://vuejs.org/v2/guide/components.html#Single-Slot)

> Parent content will be discarded unless the child component template contains at least one `<slot>` outlet

So if I try to do what the example suggests (Check here: https://jsfiddle.net/vrdx4d43/) I will obtain the contents of the child, not parent's content. If I do add an slot I will see both, so, the example cannot be replicated? If so, I think is not a good example, in any case it's confusing to me.

**Comment by chrisvfritz** [comment]
@Hacktivista The example seems to be replicated in the fiddle you provided, because you didn't include a `<slot>` in the parent - and so that message from the parent was discarded, just as the docs warned.

Either way, we're about to release a rewrite and reorganization of the components docs, which you can [preview here](https://deploy-preview-1482--vuejs.netlify.com/v2/guide/components-slots.html). I'd love to hear if the new content clarifies slots for you. 🙂

**Comment by Hacktivista** [comment]
The problem is that the affirmation "Parent content will be discarded" contradicts the affirmation "The answer is the parent" (and thus make the whole "Compilation Scope" subsection invalid).

The new "Compilation Scope" subsection is clearer.

**Comment by chrisvfritz** [comment]
Glad to hear the new section is clearer! 🙂 Thanks for taking a look. I'll close this then, as it should be released in the next week.
