### ISSUE TITLE
`Keep-alive` needs a demo to be more clear

### ISSUE THREAD

**Issue by sdras** [vuejs/vuejs.org#1493]
`keep-alive` is extremely powerful and right now the docs leave this pattern up to the imagination a little too much- I'd like to build out a demo that makes it clear at a glance how useful this can be.

**Comment by chrisvfritz** [comment]
It might be useful to build combine the tabbed interface and blog posts demos to create a realistic problem for this, like [in this fiddle](https://jsfiddle.net/chrisvfritz/9mh4hdff/). Then when we could point out how when switching tabs, the selected post resets because the component is created again from scratch. Or, maybe something with an `<input>`/`<textarea>` on a new _Contact_ tab.

What do you think?

**Comment by sdras** [comment]
Yes! Great idea.

**Comment by chrisvfritz** [comment]
Cool! I liked the idea so much I just implemented it. 😄

**Comment by sdras** [comment]
High fives
