### ISSUE TITLE
[cookbook idea] Simple, customisable static icons using provide / inject

### ISSUE THREAD

**Issue by davestewart** [vuejs/vuejs.org#1508]
A cool addition to the icons example would to use `provide/inject` rather than building a bunch of discrete icon files and having to import them all.

This way, you only ever need to update the `icons.js` file, and provide/inject allows the single Icon class to render different content without any additional edits or imports.

Additionally, you can also just save icons as raw SVGs which keeps them editable AND previewable!

Gist here: https://gist.github.com/davestewart/54b6823a76500fdcdd918fc5ce575d4c

**Comment by egoist** [comment]
I prefer using `icons` directly over `provide/inject`, like:

```js
// Icon.js
import icons from './icons'

export default {
	props: ['name'],
	render(h) {
		return h('span', null, icons[this.name])
	}
}
```

**Comment by sdras** [comment]
I really don't like this way of working because it's not very editable, you can't easily add props or adapt pieces of the icons to animate, but the cookbook isn't just about my preferences :) If you want to write up a recipe example, happy to show other ways of working, too. It would be great if you could pick a different way to name it so that people could distinguish between the two recipes.

**Comment by davestewart** [comment]
> I really don't like this way of working because it's not very editable, you can't easily adapt pieces of the icons to animate

@sdras Yeah, this really is for quick static icons.

Have just seen a little trick from @chrisvfritz to load a folder of files, which I've adapted to load all icons in a folder, and it works great:

```js
const req = require.context('.', false, /\.svg$/)

export default req
  .keys()
  .reduce((hash, filename) => {
    const id = filename.match(/\.\/(.+?)\.svg/)[1]
    hash[id] = req(filename)
    return hash
  }, {})
```

> I prefer using icons directly over provide/inject, like:

@egoist We used `provide/inject` as we had a more complex icon template and wanted to decouple it across projects.

The import vs inject comparison would be good for the "Other patterns" section though!

Re: the functional component; it doesn't have props, so you can't add things to it like "size" or "color".

Really the thrust of the PR was a recipe for icons with the **absolute minimal setup** which, frankly, when you're developing a site with bigger fish to fry and designers throwing new icons on a whim at you, is what you want.

Happy to let this percolate for a while to garner more thoughts...

**Comment by sdras** [comment]
We already address an even faster way of including icons in the style you mentioned in the alternative patterns section of this recipe, though. Both svgo-loader and svg-sprite-loader are faster versions of the above, svgo-loader has the added benefit of also optimizing the icons. I don't really see a benefit that this approach addresses that those two don't cover. So if the thrust is absolute minimal setup, I'm not sold on this approach. It sounds like what I might need to do is to expand my description of those two tools to avoid this kind of confusion.

Chris' excellent loader is already something we've talked about including, but I don't think we'd limit it to a recipe about icons, it probably deserves a recipe of it's own with broader scope.

Does that make sense?

**Comment by davestewart** [comment]
Hi Sarah,

I certainly agree with you about benefits of picking the right approach. We had no luck with the sprite sheet plugin last year (can't remember why now - it might be time to try it again).

But with regards to the cookbook article, what doesn't make sense is the overall approach to essentially size and color a static icon.

It seems for each SVG file...

You have to:

- open it in a text editor
- remove comments, declaration, SVG root node (making it un-editable and un-previewable, and crap for version control)
- wrap the contents in a template node
- save the file as a new Vue component

Then to use:

- import the icon component
- declare the component in the containing component
- write the `<icon-base></icon-base>` markup, optionally adding width, height, color as appropriate
- compose the `<icon-blah>` declaration

It's just lots of work to seemingly make Vue look cool.

As you say, there are faster ways for static icons, and is the reason I dropped the tweet / made the issue in the first place.

Apologies if i'm missing the point, but the static stuff just feels like justification for the "Editable SVG Icon Systems" title, especially as it doesn't carry over into the animated section.

I think if the recipe was just about animated icons, it would be really useful.

Again, sorry if this sounds critical for the sake of it, it's really not meant like that.

**Comment by sdras** [comment]
The cookbook is intended to show people a deep dive into a certain way of working, while also showing alternative methods. The other way of working you showed skips out on many important steps: optimizing, making the SVGs accessible, and making them editable. Using icons in myriad ways across a codebase is extremely important. Optimization is also an important step- I worked on a codebase where I reduced the load from 10 seconds to 2 seconds by properly optimizing their SVG! 

Even using the loaders have a number of steps to have them work properly.

Every way of working has it's benefits, and it's pitfalls. If you'd like to submit a recipe, I'm all for it. If this issue is submitted because it's not your personal preference to work the way that the recipe suggests, I'll close the issue, you don't have to work that way :)
