### ISSUE TITLE
Cookbook Guidelines for Recipes all start with "1."

### ISSUE THREAD

**Issue by VsevolodTrofimov** [vuejs/vuejs.org#1515]
![image](https://user-images.githubusercontent.com/10118898/37701283-6c87d700-2cff-11e8-9ae1-c1461fbb15ef.png)

Not sure if this is a bug or intended writing.

**Comment by sdras** [comment]
I believe this is because you have an old version cached, can you please try to hard-refresh the page and let us know if you are still seeing the same thing or if it goes away? A couple of other people who reported this needed their cache cleared to see it correctly. 

If it doesn't go away, please let us know what browser/OS you are on. Thanks!

**Comment by VsevolodTrofimov** [comment]
Yeah, it's fixed now.
Seems more like docs website itself was caching it, as I initally saw it in vue docs pwa (which I opened for the first time after cookbook release (maybe sw updated silently though) ).

**Comment by sdras** [comment]
Oh, that's good to know. I had assumed people had visited the page before because I just rearranged it. I'll look into this, thank you!
