### ISSUE TITLE
Clarify two different uses of `keys` near eachother in intro

### ISSUE THREAD

**Issue by sdras** [vuejs/vuejs.org#1540]
I just had to clarify for someone just starting [this section](https://vuejs.org/v2/guide/list.html#v-for-with-an-Object) and [the section following](https://vuejs.org/v2/guide/list.html#key) because we use keys for both but they're referring to different types of keys.

**Comment by afontcu** [comment]
Hi! An simple solution would be rephrasing the first section:

`You can also provide a second argument for the key:`

to something like

`You can also provide a second argument for the name of the property`

You just said "property" in the first sentence of the section, so I guess that'd make sense.


---

I was thinking about it, and I came to the realization that, since we are supposed to _always_ set the `:key` prop along with `v-for`, shouldn't the docs talk about this requirement event before talking about the `(item, key, value)` structure?

My take on this is that the `:key` requirement should be the first thing the reader is exposed to when reading this section.



I'll happily make a PR to solve this issue.

Hope it helps! Thanks for ur job :)

**Comment by sdras** [comment]
I think that's an excellent point @afontcu and we'd gladly take a PR for it.

**Comment by sdras** [comment]
For reference- @chrisvfritz does have a PR open already that we're working on here, but it doesn't yet take into consideration your suggestion: https://github.com/vuejs/vuejs.org/pull/1554

**Comment by afontcu** [comment]
Cool! that PR is a great starting point, so I'll let Christ handle it :)
