### ISSUE TITLE
Document that `data()` and computed properties receive the vm as their first argument

### ISSUE THREAD

**Issue by LinusBorg** [vuejs/vuejs.org#1541]
Since one of the recent updates, `data` and computed properties receive the `vm` as their first argument, so we an do this, for example:
```javascript
props: ['name'],
data: vm => ({ NAME: vm.name + '!'})
```
```javascript
computed: {
  hello: vm => `Hello, ${vm.NAME})
}
```

Interactive example: https://jsfiddle.net/Linusborg/j3fwLe37/

This is not documented so far, but should be.

We just had a feature request to implement this for computed props, for example: https://github.com/vuejs/vue/issues/7922

**Comment by Loilo** [comment]
I think it would be sufficient to change the block that [currently discourages](https://vuejs.org/v2/api/#computed) using arrow functions to something like "pay attention to this if you want to use arrow functions".

Do you agree?

I'm not 100% confident in my English writing skills, but since it's going to be reviewed anyway, I'd be happy to attach a PR. 👍
