### ISSUE TITLE
PDF version of doc ?

### ISSUE THREAD

**Issue by alfredking1988** [vuejs/vuejs.org#1610]
Hi, the current doc is very good. It would be even better if they can be printed. 

I know the API doc is already in one page so it can be printed easily. 
But the Guide, Style and Cookbook docs are not.

Is it possible to have the pdf version or one page version of doc ?

Thanks

**Comment by chrisvfritz** [comment]
Thanks for the suggestion! 🙂 Improvements to our print styles are always welcome, but I don't think we'll offer a PDF converter or another way to easily print out the entire website, unless it's very simple and easy to maintain. 

The reason is that printing a page of the docs is already relatively rare, so I'm thinking that wanting to print out _everything_ will be even more rare. Plus, we make updates to the docs almost every day, so it wouldn't take long for a printed version to become inferior to the online version.

**Comment by alfredking1988** [comment]
Got it !  

But will you consider provide a one page version, just like the docs of node.js, it has pages for each sections and also a single page version for all sections. 

Thank you

**Comment by chrisvfritz** [comment]
I'd be open to a PR that generates a single-page version of the guide. 🙂
