### ISSUE TITLE
Preact in comparisons guide

### ISSUE THREAD

**Issue by bencooper222** [vuejs/vuejs.org#1613]
I've often heard that Preact is a good solution to the difference in load time and perf between React and Vue. I don't have nearly the expertise to evaluate that claim but would definitely appreciate a section under the React comparison section (it probably doesn't need its own section - Preact is super similar to React) about how Vue compares to Preact.

**Comment by chrisvfritz** [comment]
> I've often heard that Preact is a good solution to the difference in load time and perf between React and Vue.

If you look at the [3rd-party benchmark](http://www.stefankrause.net/js-frameworks-benchmark7/table.html) we link to, you'll see that all 3 are extremely fast. My impression is that the big perf advantages Preact used to have over React have largely disappeared.

> [I] would definitely appreciate a section under the React comparison section (it probably doesn't need its own section - Preact is super similar to React) about how Vue compares to Preact.

As you said, Preact is very similar to React, so there's not much to say. I think the main difference is that because Preact isn't fully compatible with everything in the React ecosystem, some advantages of React's ecosystem don't apply. So if someone is choosing between React (or something React-like) and Vue, I'm not sure there's anything we could add that would better inform that decision. 

Does that make sense?

**Comment by bencooper222** [comment]
Definitely does - could we include a version of what you just said on the website?
