### ISSUE TITLE
vuejs.org documentation for filter

### ISSUE THREAD

**Issue by larsmars** [vuejs/vuejs.org#1645]
Reproduction link
https://012.vuejs.org/guide/custom-filter.html

This is my top google hit when I search for vue.js custom filter.

What is expected?
Documentation should have version number.
The two way filter guide is not working/depricated, should be labeled removed/depricated/replaced and link to solution in documentation
(remove or indicate old/outdated documentation)

What is actually happening?
The two way filter guide is not working
On the link provided, the only thing nearly indicating any version number is the text: "Looking for 0.11 docs.

**Comment by chrisvfritz** [comment]
Hm, a couple (not mutually exclusive) options come to mind. We could:

- Add a banner to all previous versions of the docs, making it clearer that it does not refer to the most recent version of Vue.
- Somehow tweak the SEO so that older docs will only show up in search results when that specific version number is included in the search. Not sure if this is possible. 😕  
- Add noindex to all previous versions of the docs. This would be pretty extreme, so I probably don't see it happening.

**Comment by Jinjiang** [comment]
Btw I found [6 legacy docs in different versions & languages](https://github.com/vuejs?utf8=✓&q=vuejs.org):

* https://011.vuejs.org
* https://012.vuejs.org
* https://012-cn.vuejs.org
* https://v1.vuejs.org
* https://v1-cn.vuejs.org
* https://v1-jp.vuejs.org

We should do the same thing to all of them if any action decided.

Thanks.

**Comment by larsmars** [comment]
Easy and effective implementation as @chrisvfritz commented: some kind of indication/banner that this documentation is obsolete and a referance to updated/current version. Frustrating to spend time on an implementation, to later find out that the implementation is outdated/not working.

**Comment by shentao** [comment]
Sorry for the delay. Just created a script that will inject a small notification on the pages where it is included. I will be adding PRs to the places mentioned by @Jinjiang over the next few days.
https://cdn.jsdelivr.net/gh/shentao/vuejs-outdated-docs-modal@v1.2/prompt.min.js

**Comment by chrisvfritz** [comment]
This has now been fixed. 🙂 Thanks @shentao!!

**Comment by shentao** [comment]
At last 😞
