### ISSUE TITLE
The client-side rendered is not matching server-rendered

### ISSUE THREAD

**Issue by giorgi94** [vuejs/vuejs.org#1707]
Hi, I am writing website with using vue and ssr, and console logs this warning 

`[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

And when I display only server side, it matches client side, so I don't know what is a problem. Here is part of code

```
<template lang="pug">
#topcontentleft(v-if="category")
    .topcontentleft
        .categorylist
            .categoryblocktitle {{category.title}}
            .categorylistitems
                .categorybigitem(v-if="category.leading")
                    .categorybigimg
                        router-link(:to='articleURL(category.leading)')
                            img(:src='category.leading.images["354x230"]', alt='', align='left')
                    .categorybigdate {{category.leading.publish_up}}
                    .categorybigtitle
                        router-link(:to='articleURL(category.leading)') {{category.leading.title}}
                    .cls
                .categorylistitem(v-for="(article, index) in category.articles", :key="index")
                    .categoryitemimg
                        router-link(:to='articleURL(article)')
                            img(:src='article.images["262x170"]', alt='', align='left')
                    .categorybigdate {{article.publish_up}}
                    .categoryitemtitle
                        router-link(:to='articleURL(article)') {{article.title}}
                    .cls
</template>
```
And when I comment remove `.categorybigitem` this div, it doesn't throw the warning.

**Comment by LinusBorg** [comment]
Hello ..

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
