### ISSUE TITLE
List rendering documentation needs v-model example

### ISSUE THREAD

**Issue by Ermish** [vuejs/vuejs.org#1735]
The documentation doesn't appear to include a clear example to properly use `v-for` in combination with a child `v-model`.

Example:

```
<div v-for'user in users'>
   <user-form v-model='user' />
</div>
```

**Comment by chrisvfritz** [comment]
Thanks for the issue! 🙂 There's not actually anything different about using v-model when it's inside of v-for. What information do you feel like you were missing?

**Comment by leopiccionia** [comment]
@chrisvfritz I think that a common gotcha is that `v-model` should refer to a property of an object. It won't work with an array of primitive values -- it will actually trigger a compilation error, but I don't remember being warned by the docs.
https://jsfiddle.net/leopiccionia/e0gqa4jr/

**Comment by chrisvfritz** [comment]
@leopiccionia Hm, I'm a bit torn here, because this isn't actually specific to Vue here - it's just the way JavaScript works. For example, in this code:

```js
var list = ['a', 'b', 'c']

list.forEach(function (item) {
  item = 'something'
})
```

You wouldn't expect the `list` array to be affected, because `item` stores a value rather than a reference (only arrays and objects are passed by reference). I'm going to close this for now, because I'd like to steer away from teaching more complex JavaScript in the docs.

I'm open to further discussion in this issue though.
