### ISSUE TITLE
Specifically which browser versions are supported?

### ISSUE THREAD

**Issue by arbarrett** [vuejs/vuejs.org#175]
I notice that firefox 4 to 10 do not work for a number of the examples in the examples page.
e.g. http://vuejs.org/examples/grid-component.html
The following is a link to the screenshots produced for those versions:
https://www.browserstack.com/screenshots/16186472da07af3c3696983908409a843f325bf4
The site seems to indicate that ECMAScript 5+ is required, but my understanding is that firefox 4+ has implemented nearly all of that.
The Galaxy S2 and Galaxy Note (original) seem to show nothing at all for that example page, but maybe the browser used is pre ECMAScript 5.
Is there a formal list of what browsers are supported?
(I know all the browsers and devices I have mentioned are quite old, so no problem if not supporting, I would just like to know).
Thanks,
Andrew

**Comment by yyx990803** [comment]
Hmm, don't really have a comprehensive list for all the legacy ones...

For Firefox - since it auto-upgrades since version 16, support for any version before that cannot be guaranteed.

For Android - every release is tested against an Android 4.2 browser, but versions before that cannot be guaranteed.

**Comment by arbarrett** [comment]
Thanks for the answer Evan.
