### ISSUE TITLE
One root element inside template v-if example

### ISSUE THREAD

**Issue by BlitZz96** [vuejs/vuejs.org#1766]
In the [conditional](https://vuejs.org/v2/guide/conditional.html#Conditional-Groups-with-v-if-on-lt-template-gt) part of the documentation, you are applying a `v-if` on the `<template>` tag. 

For the sake of the example, I agree. But since vue 2.0, you can only have one root element inside the template, or am I mistaking?

**Comment by kinsomicrote** [comment]
I think this example assumes that the `<template>` is not the root element. Something like this:

```
<template>
	<div>
		<template v-if="ok">
		  <h1>Title</h1>
		  <p>Paragraph 1</p>
		  <p>Paragraph 2</p>
		</template>
	</div>
</template>
```

**Comment by BlitZz96** [comment]
That seems like weird semantics to me, but I suppose you can be right.
I have not observed nested template elements in the docs. However, it's crowded with single root template examples. 

I just find this doc example a bit misleading.

**Comment by leopiccionia** [comment]
`<template/>` is a HTML5 ordinary tag ([see spec](https://html.spec.whatwg.org/multipage/scripting.html#the-template-element)), just like `<script/>` and `<style/>`,  it's **not** Vue-specific.

On a SFC, Vue uses the top-level `<template/>` to find the root element of component and, currently, you can have only one root element.

Inside the template itself, `<template/>` is more likely to be found with more than one child element, like docs example. The following
```html
<template v-if="ok">
  <h1>Title</h1>
  <p>Paragraph 1</p>
  <p>Paragraph 2</p>
</template>
```
is clearer (specially when combined with `v-else-if` and `v-else`) and has better performance (since it'll be compiled into a single `if` clause) than 
```html
<h1 v-if="ok">Title</h1>
<p v-if="ok">Paragraph 1</p>
<p v-if="ok">Paragraph 2</p>
```

**Comment by BlitZz96** [comment]
I was not too familiar with the html5 tag `<template>`. However, the specs makes sense to the example indeed.
