### ISSUE TITLE
Core search functionality not working

### ISSUE THREAD

**Issue by meetzaveri** [vuejs/vuejs.org#1773]
### What I got?
No results as it displayed the previous content(default one).

### What was expected?
According to keywords as an input in search, the results should be displayed with content containing those keywords.

### Engine
Chrome - Version 68.0.3440.106

**Comment by Haroenv** [comment]
I looked at the search settings, and it seems like the version doesn't get picked up as a facet anymore, which means that there's no results; since the search is filtered on "v2". I'm not sure which change this could be, both the Algolia settings haven't been changed in a while, neither has this docs site.

config here: https://github.com/algolia/docsearch-configs/blob/master/configs/vuejs.json

cc @s-pace, who has more info on DocSearch than I have

**Comment by moumen-soliman** [comment]
@Haroenv I think it's related to query function, If you looked at URL there is no query after hit enter in search, So I think there is no communication between input field and a component of search or something like that, If problem in configuration at least query will print in URL

**Comment by s-pace** [comment]
Sorry for the wrong update.

Fixed by https://github.com/algolia/docsearch-configs/commit/b8bc683b80cc5f2816c9b2e2f855f67b8bf1012e

@moumen-soliman We do a query at every keystroke. You do not need to press enter.

**Comment by meetzaveri** [comment]
Okay, so now I am closing this issue as problem is fixed. Tested search functionality and its working perfect as before!
