### ISSUE TITLE
Can you put Good code before Bad code in Style Guide?

### ISSUE THREAD

**Issue by klondikemarlen** [vuejs/vuejs.org#2063]
I find that when reading something, I read things in order of importance from top to bottom. And I find that Good code style to be more useful to know in the long run than Bad code style.

This is a duplicate of https://github.com/vuejs/vuejs.org/issues/1670 but that issue is closed and I feel this is still relevant (and I can't reopen that one).

**Comment by sdras** [comment]
Just so I understand- are you proposing that we put good first, then an explanation about why it's good and then the bad? 

I could go either way on it, because I see a pro and con for each:
* Good before bad doesn't [bury the lede](https://style.mla.org/dont-bury-the-lede/)
* Bad before good gives less context on reading
I assume the major difference is whether you're really reading through or skimming- if you're skimming, having bad go first is an antipattern.

@phanan  @NataliaTepluhina, what do you think as you read through it? Interested in getting a few perspectives here.

**Comment by phanan** [comment]
IMO this is very subjective. If instead it was good before bad, there would be someone else suggesting the other way around anyway (me 😄 ). So let's leave it as-is.

**Comment by klondikemarlen** [comment]
@sdras just swapping good/bad order so good is first. I find that when reading, I like to read down the page expecting the important stuff first, then if I have time or am lost I read further to get more context. I find this to be the prevalent style of any document except novels. As the entire Vue.js documentation is very succinct, I would suggest following the same style used my news articles (important stuff gets higher precedence). As you mentioned this becomes especially important when skimming through the docs, and lets face it, people will be skimming more often than reading.

**Comment by sdras** [comment]
I think @phanan has a point here :) closing this out.
