### ISSUE TITLE
[cookbook] Form validation throws CORS error for a codepen sample

### ISSUE THREAD

**Issue by msamsel** [vuejs/vuejs.org#2391]
Hi,

when I read this article: https://vuejs.org/v2/cookbook/form-validation.html#Server-side-Validation I've noticed that the linked sample is not working properly.
In the section "Server-side Validation" the codepen doesn't make a server-side validation due to CORS error. I followed also a link to API and try to make a direct call to it from my browsers and it looks like server is not available any longer.
<img width="695" alt="Screenshot 2019-11-17 at 10 49 51" src="https://user-images.githubusercontent.com/9017322/69005897-80a72180-0928-11ea-87a7-2fbb3e2babdc.png">

**Comment by cfjedimaster** [comment]
Unfortunately there probably isn't a good answer to this. Any serverless fix like this will be based on someone's free account which could expire, the author could die, etc. I think the best thing would be to simply show the code and NOT have the user actually run it so we don't have to worry about it. I can do an edit in that fashion, but I'd like to hear from @sdras first on what the Vue folks would like.

**Comment by sdras** [comment]
I mean, it's always ideal that the user can run the code themselves to play around with it. Especially as a cookbook recipe.

Raymond, can you use your Netlify account? That account has some protections, that's probably as best we can do to ensure longevity here. If it turns out to not work, it's fine then to remove the codepen and keep the code, making the URL be something that shows it's an example.

**Comment by cfjedimaster** [comment]
I'm happy using something on Netlify if yall (the Vue you, not the Netlify you ;) are fine with it. I'm busy this week and it's the holidays, so it may be the week after Thanksgiving.

**Comment by sdras** [comment]
Yes, it's the Vue me speaking :) you can use another service as you like as long as it's somewhat protected in the same fashion.
