### ISSUE TITLE
Fix BlackLivesMatter banner

### ISSUE THREAD

**Issue by genkaignatev** [vuejs/vuejs.org#2616]
Hi, guys. Today I tried to block BLM banner and got that view bug:
![изображение](https://user-images.githubusercontent.com/66470471/83865992-c6de9980-a72f-11ea-847d-9d68b6bb6dcb.png)
Please, add possibility to hide this banner. Or you can fix banner code for correct hiding by AdBlock.
Of course, I could do it by myself, but don't know how would community feel about this.

Why I created this issue? Just because we must respect ALL people. And I think there are many people in our community outside the politics

P.S. Of course, if you think community can't be outside the politics, the best way to close this issue is changing BlackLivesMatter to AllLivesMatter. This is my opinion and I want to listen other developers.

P.P.S. Why am I posting this issue from new account? Because I'm afraid of being bullied by the community and social justice warriors.

**Comment by dvoyakiy** [comment]
Completely agree with you. We must respect all people, because every life matters!

**Comment by dvoyakiy** [comment]
btw they're definitely gonna ignore and close this issue

**Comment by genkaignatev** [comment]
> 
> 
> btw they're definitely gonna ignore and close this issue

Maybe, but I not yet lost my faith in the mind and true justice.

**Comment by ZuevArseniy** [comment]
I disagree. If banner will be removed, I expect many black programmers will stop using Vue and contributing to Vue, and it will be a huge loss for the community

**Comment by dvoyakiy** [comment]
> I disagree. If banner will be removed, I expect many black programmers will quit using Vue and contributing to Vue, and it will be a huge loss for the community

Man, you got bipolyar ochka
![image](https://user-images.githubusercontent.com/40234487/83877098-9ce2a280-a742-11ea-851f-629e816048b9.png)

**Comment by ZuevArseniy** [comment]
@dvoyakiy I was trying to be thin
Pls remove

**Comment by dvoyakiy** [comment]
> @dvoyakiy I was trying to be thin, slishkom tonko vyshlo
> Pls remove

done

**Comment by emptyhere** [comment]
Black lives matter then other lives? Stop left-wing fascism.

**Comment by DirtHunter** [comment]
> Black lives matter then other lives? Stop left-wing fascism.

Can't tell if you're just thick, racist or both, it's not OnlyBlackLivesMatter. It's BlackLivesMatter.

**Comment by emptyhere** [comment]
> 
> 
> > Black lives matter then other lives? Stop left-wing fascism.
> 
> Can't tell if you're just thick, racist or both. It's not OnlyBlackLivesMatter, it's BlackLivesMatter.

You say that the lives of people with some skin color are matter than others, but I am racist. You have some logic problems.

**Comment by alfaproxima** [comment]
I beleive that our technological field is not a place for some of a political/ideologic mottos. So thumb's up.

**Comment by Coloruts** [comment]
Totally agree. Remove this racist banner.

**Comment by sdfrefdgdsf** [comment]
i ve never had an account here but i wanna say NOT ONLY BLACK lives matter.

**Comment by kenar88** [comment]
Every time I see this banner the question arises: what about myself and my family? We are not black, what about our lives, our lives don't matter? This banner is 100% racist, this is my opinion.

**Comment by yyx990803** [comment]
1. It is Vue team's freedom to show the message.

2. It is your freedom to disagree with the message. But this banner does not prevent you from reading the docs so it doesn't create any practical inconveniences to you.

3. Using an Ad Blocker when browsing Vue docs blocks some of our sponsors and ads - which is what makes the project financially sustainable, so we are not interested in entertaining any request related to Ad Block usage.

How you look at BLM depends on how you interpret it. If you think it means "only black lives matter" or "black lives matter more than others", then I can tell you that is not how the Vue team or most supporters of the movement interprets it. The motto emphasizes black people because they are the race that is currently suffering the most from racial discrimination, but we intend to use it as a message against all forms of racism. The reason why "all lives matter" should not be used isn't that it's wrong, but is because under the current context it has been appropriated by actual racists to use as a weapon to detract from the voices against racism. It would be more productive to focus on the shared spirit against racism rather than on why the motto only includes a specific race.

If you live in a place where there are racism against non-black people, the Vue team firmly stands against those types of racism too. If you are lucky enough to live in a place where racism does not exist, all it takes from you is a little bit of empathy and you can ignore the banner and move on. If you insist on interpreting it in a way that offends you after the above explanation, it is your freedom to stop reading our docs until we remove the banner.
