### ISSUE TITLE
Partials are missing from the guide

### ISSUE THREAD

**Issue by mitar** [vuejs/vuejs.org#283]
I just discovered them in the API, but they are missing in the guide.

**Comment by jdittrich** [comment]
* I wonder what their advantage over components are
* Seemingly they are not available in 2.0 anymore: https://github.com/vuejs/vue/issues/2873

**Comment by chrisvfritz** [comment]
There are no real advantages to partials. They're a fallback for components without a root element in 1.x and offer only a subset of the features normally available to a component. A warning about their limitations could be a good addition to the components guide.

**Comment by chrisvfritz** [comment]
Whoops! Not sure what I was thinking when I wrote this earlier. It seems "partials" were translated to "fragment instances" in my mind somehow. 😅  I think I'd prefer to leave partials out of the guide for now, since they deprecated in 2.0 and can be abused sometimes. Sticking to the component model is a better way to go almost all the time.
