### ISSUE TITLE
Is it possible to get the this.expression in $watch like a custom directive?

### ISSUE THREAD

**Issue by happilymarrieddad** [vuejs/vuejs.org#330]
Hey Guys/Gals,

Is it possible to get the   this.expression like you can in a custom directive in a $watch that is "watching" a deep:true object? https://vuejs.org/guide/custom-directive.html

In other words, is it possible to get whatever is passed into v-model in the watch function?

```
data() {
    return:{
        users:[{ id:1,name:'Nick',email:'nick@mail.com' },{ id:2,name:'John',email:'john@mail.com' }]
    }
},
watch:{
    'users':{
        handler(val,oldVal) {
            socket.emit('change-user-data',{ field:this.expression,value:val })
        },deep:true
    }
}
```

Currently I have to do this
```
data() {
    return:{
        users:[{ id:1,name:'Nick' },{ id:2,name:'John' }]
    }
},
watch:{
    'users.name':{
        handler(val,oldVal) {
            socket.emit('change-user-data',{ field:'name',value:val })
        }
    },
    'users.email':{
        handler(val,oldVal) {
            socket.emit('change-user-data',{ field:'email',value:val })
        }
    }
}
```
I think you can see how this doesn't scale if there is like 100 fields in the users table which is the case for a lot of objects on our production app.

HTML (in jade) would look something like this
```
input.form-control.input-sm(type='text',v-model="user.name",debounce="500")
input.form-control.input-sm(type='text',v-model="user.email",debounce="500")
```

I hope that makes sense. Thanks!

- Nick

P.S. - if there is someone who wants to do this with custom directives it works pretty easily that way.

**Comment by happilymarrieddad** [comment]
oh and the html (in jade) would look something like this

```
input.form-control.input-sm(type='text',v-model="user.name",debounce="500")
```

**Comment by happilymarrieddad** [comment]
BTW, if there is someone who wants to do this with custom directives it works pretty easily that way.

**Comment by LinusBorg** [comment]
Hello ..

Thank your for your interest in this project.

However, your issue is a usage/support question, and this repository is about the `vuejs.org` website. Therefore, your issue has nothing to do with this repository. 

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).

IF you want to introduce this as a feature request, please re-open this issue in the right repository: github.com/vuejs/vue

That being said, a quick tip: Using watchers for this is not a suggested pattern, . you should rather do something like this:
```jade
input.form-control.input-sm(type='text', v-bind:value="user.name" @input="handle(user.name, 'name', $event) | debounce 500"
```

```js
export default {
  methods: {
    handle(obj, field, e) {
      Vue.set(obj, field, e.target.value)
      socket.emit('change-user-data',{id: obj.id, field: field,value: e.target.value })
    }
  }
}
```
*(Note: the code probably does not make that much sense as the server receiving this info does not know the id of the user that was changed, but it was like this in your example so I kept it like this.)*

It's a bit more verbose, but you only need one method, and since data changes and socket emits are explicitly handled in the same place, it's much clearer what it going on.

The way watchers currently work does not easily allow to get the changed object when watching an array, so your suggestion is probably not a realistic one.

**Comment by happilymarrieddad** [comment]
The way you did it works perfect for me. Thanks!
