### ISSUE TITLE
Add State Management Example

### ISSUE THREAD

**Issue by scottsword** [vuejs/vuejs.org#377]
I understand the gist of what is going on in this section as I have followed this pattern before in Angular. After I'm done reading this I'm left scratching my head as to how to actually implement it. It would be *great* to have a working example of this.

#### Current Example https://vuejs.org/guide/application.html#State-Management
```
var store = {
  state: {
    message: 'Hello!'
  },
  actionA: function () {
    this.state.message = 'action A triggered'
  },
  actionB: function () {
    this.state.message = 'action B triggered'
  }
}

var vmA = new Vue({
  data: {
    privateState: {},
    sharedState: store.state
  }
})

var vmB = new Vue({
  data: {
    privateState: {},
    sharedState: store.state
  }
})
```

Questions I have after reading this:
- Don't vmA and vmB still have direct access do modify the store and therefore cause bad side effects?
    - How does vmA and vmB modify the parent data privately?
- How do we mount both of these Vue instances without a router?
- Is it possible to protect upstream data in Vue.js when it is a complex data structure (since I know only primitives can be one-way)?

**Comment by chrisvfritz** [comment]
After thinking about this some more, I don't think we want to make this section any more detailed,  because we don't actually want you to build your own state management system. You should just use vuex instead. We walk through a simple state management solution just to introduce you to the concern of state management and some of its complexities. 

To answer your questions though:

- Yes, but it depends on what you mean by "side effects". Since the shared data is reactive, changing it in `vmA` will also trigger the reactivity system of `vmB`. Vue doesn't care where it happened.
  - They don't. The shared data is shared, rather than each vm owning a private instance of it.
- You don't do anything special - the fact that some data is shared does not affect how Vue instances are mounted or how you switch between components, etc.
- You'd need immutable data for this or just some conventions that limit access to the store state. In vuex for example, all updates are made through mutations, which are triggered by actions.
