### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by Bernardo-Castilho** [vuejs/vuejs.org#388]
We recently finished a module with Vue components encapsulating our suite of JS controls: https://github.com/Bernardo-Castilho/WijmoVue.

Creating the module was very easy, and I hoped it would work with Vue 2 as well. Unfortunately, it does not. I spent some time learning Vue 2 and trying to port the code. The first thing I tried was simply replace "attached" with "mounted". When I did that, our controls were created and added to the page as expected. But (very strangely), Vue seems to hijack our property getters and setters, so the controls misbehave in strange ways.

I don't know if this is a bug in Vue 2, a bug in my wrapper code, or if there's a design flaw in the wrappers (which are really quite simple). I will keep investigating, and hoping someone who knows Vue better than I do will take a look at my original wrappers and tell me what I'm doing wrong:

     https://github.com/Bernardo-Castilho/WijmoVue

Thanks in advance for any help/tips. We would really like to support Vue 2 in our products, we love the framework.

**Comment by chrisvfritz** [comment]
@Bernardo-Castilho Looks like a cool project! Taking a very quick glance, you may want to look into [mixins](http://vuejs.org/guide/mixins.html) to share configuration between components. For further help/discussion though, I'd suggest posting this question on [the forum](http://forum.vuejs.org/), since it's not specific to the Vue website or docs, which means I'll have to close this. 😕

**Comment by Bernardo-Castilho** [comment]
Posted in the forum. Thanks!
