### ISSUE TITLE
Expand SSR: Routing + SEO (Title, Meta, etc)

### ISSUE THREAD

**Issue by blake-newman** [vuejs/vuejs.org#406]
- Add more information on SEO with SSR
- Add examples highlighting how to improve SEO with SSR
  - Example: meta tags management

**Comment by johnleider** [comment]
Any updates on this?

**Comment by chrisvfritz** [comment]
@johnleider https://twitter.com/slicknet/status/782274190451671040

**Comment by blake-newman** [comment]
@johnleider I am currently implementing this on my personal website, it should be fairly easy.

Once achieved ill add examples it into the guide.

**Comment by ljanecek** [comment]
It would be nice have the data of app.
There isn't any way how get the data from renderStream?
I don't know exactly how streaming works, 
but when i make emit of app here: https://github.com/vuejs/vue/blob/dev/src/server/create-bundle-renderer.js , the world is better place for me 👍 

BTW: @blake-newman i saw nothing there https://github.com/blake-newman/website/blob/master/script/server.js

**Comment by dwightjack** [comment]
Hi,

I'm trying to rewrite `vue-helmet` to be usable on SSR project. At the moment I've implemented the `<meta>` and `<title>` tags on the client, but cannot make it work on the server (not an expert ATM, but it seems that watchers and computed are not triggered?
I'm using a separate vue instance to manage the global metas state, could it be the issue?

The project is here: https://github.com/dwightjack/vue-helmet/tree/develop (`npm install && npm start`, then navigate to `http://localhost:8080/examples/`

The SSR example is here: https://github.com/dwightjack/vue-helmet/tree/develop/examples/ssr

Since it's my first attempt at vue SSR i'm pretty sure i'm making something wrong...

**Comment by dwightjack** [comment]
Hm, sorry... just realized that maybe this is not the right place to post this...

Reposted on the forum http://forum.vuejs.org/t/meta-data-with-vuejs-ssr/716/6 :P

**Comment by sdras** [comment]
Trying to go through and find possibly stale issues- @blake-newman are you still interested in adding this? At this point if we do clarify SSR and the SEO benefits, we should definitely link off to Nuxt.

**Comment by blake-newman** [comment]
I think we can close this now with SSR vue docs. They cover this nicely now.
