### ISSUE TITLE
Clarification needed on "Non Parent-Child Communication" in Guide

### ISSUE THREAD

**Issue by jvanbrug** [vuejs/vuejs.org#408]
http://rc.vuejs.org/guide/components.html#Non-Parent-Child-Communication

I tried implementing the above 2.0 example in a standalone web app:

Source: https://github.com/jvanbrug/vue-guide-examples/tree/master/09_Components/13_Non_Parent-Child_Communication

Live demo: https://jvanbrug.github.io/vue-guide-examples/09_Components/13_Non_Parent-Child_Communication/index.html

However, I am unsure where this code snippet should go:

```javascript
// in component B's created hook
bus.$on('id-selected', function (id) {
  // ...
})
```

I'm likely missing something, but I don't think the concept of a "hook" was properly motivated (or mentioned) before this point in the 2.0 Guide.

**Comment by LinusBorg** [comment]
```js
Vue.component('component-b', {
  template: '<span>A has{{ aWasClicked ? "" : " not"}} been clicked</span>',
  data: {
    aWasClicked: false
  },
  created() {
    bus.$on('id-selected', function (id) {
      // ...
    })
  }
})
```

For the future: Your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests. Therefore I close this now.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).

**Comment by LinusBorg** [comment]
@chrisvfritz We might have to refer to the term "hooks" more prominently in the guide, e.g. change the title of the section to "Instance Lifecycle **Hooks**" ?

**Comment by jvanbrug** [comment]
Thanks @LinusBorg! And thanks for the forum/gitter tip, will do 😄

**Comment by chrisvfritz** [comment]
@LinusBorg Done. 😃

**Comment by ctf0** [comment]
the current `var bus` doesnt work unless we have the components written in the same file where that var was declared or else we would get `bus.$emit is not a function` so i believe it better be
```js
window.bus = new Vue();
```
and now all would work without any issues.

**Comment by LinusBorg** [comment]
@ctf0 If they are not declared in the same file, you would likely use a module bundler, right?

Then you can simply import the bus where you need it. globals should be avoided wherever possible.

**Comment by ctf0** [comment]
u r right but the reason i added the above because https://vuejs.org/v2/guide/components.html#Non-Parent-Child-Communication in its current form wont work and user will get an error.

**Comment by chrisvfritz** [comment]
It will actually work fine, even if components are across multiple files
outside a build system. The only case where users need to do something
slightly different is when using a module bundler. In the case that they're
using advanced tooling, I don't think it's unreasonable to expect them to
know the very basics of how bundlers work. There's nothing specific to Vue
here.

**Comment by EthraZa** [comment]
Hi I'm VueJs new commer. 
I'm struggling right now to get this emit/listen thing to work. I come with an ExtJs background and there we can emit/listen to events with easy inside the app instance. The VueJs manual is at best lacking in this specific section. 
This conversation helped me to undestand that "the created hook" is the created() function of the component, I was not getting it. 
But the bus is still non existent for the components. I'm creating it in the main.js, and I'm not sure why it is not working. Creating it as window.bus worked, and again I don't understand why, since I'm using webpack to bundle things. (yeah, I'm new to webpack too)
I'll eventually work it out, but I would like to add my word here that the manual could be more clear.

I'll now say what I'm really thinking about the hole thing... For a new commer like me, I would love to see a Kitchensink example app, using all this concepts in one place with best practices and all, to speed me up. :)

**Comment by chrisvfritz** [comment]
@EthraZa Check out [our hackernews demo](https://github.com/vuejs/vue-hackernews-2.0). 🙂
