### ISSUE TITLE
[2.0] Missing global api transition

### ISSUE THREAD

**Issue by dalphyx** [vuejs/vuejs.org#410]
The transition is still remained according to the [2.0 Changes](https://github.com/vuejs/vue/issues/2873) global api section. Now it's missing from the 2.0 docs.

**Comment by chrisvfritz** [comment]
That issue is no longer the definitive document for breaking changes. I just added a comment there to redirect people in the future. See the new [migration guide](http://rc.vuejs.org/guide/migration.html) instead. In the case of reusable transitions, you can now [just use components](http://rc.vuejs.org/guide/transitions.html#Reusable-Transitions).
