### ISSUE TITLE
Lifecycle hooks/methods:  Add note not to use arrow functions for them.

### ISSUE THREAD

**Issue by LinusBorg** [vuejs/vuejs.org#411]
Arrow functions don't work for hook functions and component methods because Vue can't use `.bind()` on them to bind them to the current vm instance, so `this` will be `undefined`

But people who don't know the mechanics of Vue here often miss this.

I see a question about this on the forum or in the github issues every week at the least.

**Comment by chrisvfritz** [comment]
@LinusBorg What do you think about this kind of warning?

> Note that __you should not use arrow functions on an instance property or callback__ (e.g. `vm.$watch('a', newVal => this.myMethod())`). The reason is arrow functions bind the parent context, so `this` will not be the Vue instance as you expect and `this.myMethod` will be undefined.

Do you think that will make sense to the people you see make this mistake?

**Comment by LinusBorg** [comment]
I think the text is good, but using $watch for the example is not. It's not an option everyone uses, and not one beginners are familiar with early on. We should pick something more basic, like `mounted` or a computed prop.

**Comment by chrisvfritz** [comment]
Sounds good - and I agree about `$watch`. I only used it because it's what's in the example under [Properties and Methods](http://vuejs.org/guide/instance.html#Properties-and-Methods), which is the first place I was thinking of introducing the warning (I'd like to add versions of it with different examples to a few different places).

Do you think that's a good place to start? I was worried about adding it to the introduction, as I don't want to scare new users by mentioning Babel/ES2015 right away. Or should it only be added to the API section, under `data`, `computed`, `methods`, and `watch`?

**Comment by LinusBorg** [comment]
> Do you think that's a good place to start?

Oh, in that context I guess $watch is fine. 

> Or should it only be added to the API section, under `data`, `computed`, `methods`, and `watch`?

We should add it in those places as well.
