### ISSUE TITLE
TodoMVC Example: note that example won't work if blocking 3rd party site data

### ISSUE THREAD

**Issue by raahede** [vuejs/vuejs.org#512]
The demo app isn't adding todos on enter.

`Chrome OSX` `Version 53.0.2785.143 (64-bit)`

https://vuejs.org/examples/todomvc.html

<img width="1411" alt="screen shot 2016-10-17 at 13 46 41" src="https://cloud.githubusercontent.com/assets/391833/19436477/9b084e4e-9470-11e6-8780-46eba867efa5.png">

**Comment by LinusBorg** [comment]
Works here, Chrome 53.0.2785.143.

Have you tested it without any extensions active (i.e. in an incgonito tab)?

**Comment by raahede** [comment]
I realize now this is due to a browser setting, but it may be good to note somewhere.

**Comment by chrisvfritz** [comment]
I think I'd prefer to just fork that example so it doesn't use `localStorage`, as it's not an essential part of the demo.

**Comment by LinusBorg** [comment]
localstorage is part of the TodoMVC spec:

https://github.com/tastejs/todomvc/blob/master/app-spec.md#persistence

**Comment by chrisvfritz** [comment]
@LinusBorg Ehh, OK. 😄  We'll add a note.

**Comment by wvh** [comment]
Same problem in Mozilla Firefox 45.4.0 (Debian stretch/sid). Nothing happens on `<enter>`. I don't seem to get a security warning either in the console when I press `<enter>`.

I block third-party cookies; if I accept all cookies, it works (as mentioned on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API)).

A warning would be nice because now it looks as if Vue itself isn't working, which is probably not the impression you'd like to make to people checking Vue's examples.

**Comment by chrisvfritz** [comment]
Just added a note.
