### ISSUE TITLE
Mention Licences in Comparisons Guide

### ISSUE THREAD

**Issue by jeschkies** [vuejs/vuejs.org#533]
I'd point out that React has it's own license. I know of several cases where legal prohibited the use of React because of its license. Even if the license if not an issue it has to be check while MIT which Vue is licensed under is well known.

**Comment by chrisvfritz** [comment]
Those license issues have since been resolved. [React now uses a BSD license](https://github.com/facebook/react/blob/master/LICENSE), which is also very well-known and very similar to the MIT license.

**Comment by jeschkies** [comment]
It's actually the patent grant that can be revoked. I mean it is an issue for some developers or rather their company. Then again the comparison is probably not the right place to point this out :).

**Comment by chrisvfritz** [comment]
The patent grant has been [softened as well](https://github.com/facebook/osquery/commit/159899a303d0859eb7c3768561544c48ccea42b3#diff-7373d27f0ea94a5b649f893e20fffeda), so that Facebook can no longer use the threat of revocation as a weapon in a patent dispute they initiate. But either way, I'd rather not spread FUD in the comparison guide, especially since none of us on the team are legal experts. 

For organizations that are very strict about the software they use, I trust that they'll be able to independently research the implications of any licenses or patent grants pertaining to that software.

**Comment by jeschkies** [comment]
Good point : ).
