### ISSUE TITLE
Migration guide doesn't mention change for v-on event naming

### ISSUE THREAD

**Issue by enjikaka** [vuejs/vuejs.org#553]
The migration guide doesn't mention that `v-on:mouseUp`, `v-on:mouseDown` no longer works, and must be changed to `v-on:mouseup`, `v-on:mousedown`. (all lowercase)

That was a real tricky change to find out.

http://rc.vuejs.org/guide/migration.html

**Comment by chrisvfritz** [comment]
@enjikaka I don't think this is a Vue issue. The behavior you describe [does not seem to appear](https://jsfiddle.net/46bcghrb/) with Vue 2 in Chrome 54. It's important to note however that `mouseUp` and `mouseDown` are not guaranteed to work anyway, since they're [lowercase DOM Level 3 events](https://developer.mozilla.org/en-US/docs/Web/Events/mouseup), which are [case-sensitive according to the spec](https://www.w3.org/TR/DOM-Level-3-Events/#changes-DOMLevel2to3Changes). My guess is you're using a browser that just started complying with that aspect of the 2004 spec.

**Comment by enjikaka** [comment]
@chrisvfritz I used Chrome Version 52.0.2743.116 (64-bit) for this. In Vue 1, mouseUp worked. In 2, it didn't. So it's got to be something with Vue?

**Comment by enjikaka** [comment]
@chrisvfritz https://jsfiddle.net/d8tu6djs/ <- like this is reproduces there

**Comment by chrisvfritz** [comment]
If you could provide a fiddle demonstrating what you're seeing, that would be useful.

**Comment by enjikaka** [comment]
@chrisvfritz https://github.com/enjikaka/vue-event-test

This is a fresh `vue init webpack <folder-name>` with additon of;
```
<h2>Event tests</h2>
    <ul>
      <li><button v-on:mouseup="mouseUp">v-on:mouseup (lowercase)</button></li>
      <li><button v-on:mouseUp="mouseUp">v-on:mouseUp (camelCase)</button></li>
    </ul>
```

and

```
,
  methods: {
    mouseUp () {
      alert('Mouse up works!');
    }
  }
```

in Hello.vue.

Only the lower case one works...

**Comment by chrisvfritz** [comment]
It looks like the problem only occurs [in string templates](https://jsfiddle.net/n043gghh/). Knowing that, it looks like what's happening is that since Vue 1 uses the browser's own HTML parser, the attribute names are normalized to lowercase, since [attributes are case-insensitive](https://www.w3.org/TR/html-markup/documents.html#case-insensitivity). This then causes the `mouseUp` event - which is _not_ a valid DOM Event - to be transformed into the correct event: `mouseup`.

I'm glad we solved the mystery, but this isn't something I'll be adding to the migration guide. The fact that event names with the wrong case would sometimes work was never an intentional feature, but an unavoidable implementation quirk.
