### ISSUE TITLE
vuejs.org website translation

### ISSUE THREAD

**Issue by kazupon** [vuejs/vuejs.org#57]
In the [Event](http://connpass.com/event/10862/),
VueJS japanese user community want to translate the vuejs.org website for Japan.

I think that create a `vuejs/vuejs-ja.org` repository, and should translate in the repository.

I hope you give me the other good ideas. :)

**Comment by yyx990803** [comment]
Feel free to just fork it, it doesn't need to live under vuejs, but you can do that too :)

**Comment by kazupon** [comment]
Thank you for your idea.
I will tell to the vuejs japanese users. :)

**Comment by yyx990803** [comment]
Let me know when you haved forked it - I can have a subdomain like `jp.vuejs.org` point to the corresponding github pages.

**Comment by kazupon** [comment]
Thanks!!
That would be great!!
I [tweeted](https://twitter.com/kazu_pon/status/569413613431099392) to the vue.js japanses users, and then there was some contact from vuejs japanese users.


I forked `vuejs/vuejs.org` to [vuejs-jp/vuejs.org](https://github.com/vuejs-jp/vuejs.org) yesterday.
After this, we will translate in `vuejs-jp/vuejs.org`.

Sorry, my poor english ;)

**Comment by kazupon** [comment]
@yyx990803 
we finished translation vuejs.org of v0.11.

I'm translating some difference commits from v0.11 to v0.12.
https://github.com/vuejs-jp/vuejs.org/pull/37

We're almost there !!

**Comment by yyx990803** [comment]
Great work!
顽张って！

**Comment by kazupon** [comment]
Thanks :)

**Comment by kazupon** [comment]
Sorry to keep you waiting.

I finished translation 0.12 version.
Please check the `lang-ja` branch of vuejs-jp/vuejs.org repository.
https://github.com/vuejs-jp/vuejs.org

I invited your account to contribuers team of vuejs-jp/vuejs.org repository.
You can push `lang-ja` branch to vuejs/vuejs.org repository.

**Comment by yyx990803** [comment]
Thanks for the great work!
Just a heads up I have a few updates that are going to be released later today.

**Comment by yyx990803** [comment]
@kazupon Let me know when you have updated the translation for 0.12.1, and we can try to publish the site. What you need to do is:

1. change `source/CNAME` to `jp.vuejs.org`
2. in `_config.yml`, at the bottom, change the [deploy URL](https://github.com/vuejs-jp/vuejs.org/blob/lang-ja/_config.yml#L100) to `git@github.com:vuejs-jp/vuejs.org.git`
3. make sure the `vue` repo is side by side to the `vuejs.org` repo on your machine because the [build script needs to build and copy vue.js](https://github.com/vuejs-jp/vuejs.org/blob/lang-ja/Makefile#L9-L11).
4. deploy the site to github with `make deploy`.

I will then add `jp.vuejs.org` to my DNS records.

**Comment by kazupon** [comment]
@yyx990803 
Thanks !!
OK.
I'll try to translate 0.12.1.

**Comment by kazupon** [comment]
@yyx990803 
I'm done.
Please check the lang-ja branch of `vuejs-jp/vuejs.org`.

**Comment by yyx990803** [comment]
Woot! http://jp.vuejs.org/

For further updates, you just need to do `make deploy` in your branch. It will push to the `gh-pages` branch of `vuejs-jp/vuejs.org` (which the domain points to)

**Comment by kazupon** [comment]
OK !!
Thank you for your sincere support. :)
