### ISSUE TITLE
Problem with Declarative rendering section of guide

### ISSUE THREAD

**Issue by dflock** [vuejs/vuejs.org#583]
This [page in the guide](http://vuejs.org/v2/guide/#Declarative-Rendering) says:

> Just open up your browser’s JavaScript console and set `app.message` to a different value.

I couldn't figure out how to get this to work?

My `index.html` looks like this:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Vue Example</title>
  </head>
  <body>
    <div id="app">
      {{ message }}
    </div>
    <script src="dist/build.js"></script>
  </body>
</html>
```
and my `main.js` looks like this:

```js
import Vue from 'vue/dist/vue.js'

var myapp = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!'
  }
})
```

my "app" opens in the browser and renders:

![image](https://cloud.githubusercontent.com/assets/47756/20290563/a3f2c3e6-aa95-11e6-9383-03075c47d0fb.png)

and the Vuejs dev-tools can see/recognise it - but I can't figure out how to update the value of `message` in the console:

![image](https://cloud.githubusercontent.com/assets/47756/20290590/cc5c7944-aa95-11e6-89de-237d5ebdf765.png)

Because `index.html` has `app` as a `id`, you *can* just say `app` in the console, but that's just a DOM node:

![image](https://cloud.githubusercontent.com/assets/47756/20290649/42aab78c-aa96-11e6-92a4-77e021e67cde.png)

So I think you need to expand on this line and explain & show an example:

> Just open up your browser’s JavaScript console and set `app.message` to a different value.

**Comment by dflock** [comment]
Hmmm. Had a little epiphany and tried this on the actual guide page itself - rather than the little app I was building locally as I was going along - and it works!

So, it works on the guide page, but not in my simple little app?

**Comment by chrisvfritz** [comment]
The code as posted works perfectly. When using a module system, e.g. via Webpack or Browserify, the code in your modules are actually wrapped to... modularize them. Otherwise, they'd be very leaky, as any variables defined would be in the shared global scope. That's why when trying to access your `myapp` variable in the console, it doesn't work. Your module system is doing it's job. 😃  

We expect users of these module systems to know how they work, as they have their own documentation, but you can get your example working with `window.myapp =` to explicitly assign `myapp` to the global object.

**Comment by dflock** [comment]
Thankyou!

For anyone else wondering how to access your global stuff in a webpacked vuejs app, you can do it by typing this into the dev console:

```js
> window.myapp = window.$vm
// <- Vue$2 {_uid: 0, _isVue: true, $options: Object, _renderProxy: Proxy, _self: Vue$2…}
> myapp.message
// <- "Hello Vue!"
> myapp.message = 'test'
// <- "test"
```

More information [here](http://stackoverflow.com/questions/38134098/access-javascript-objects-from-dev-console-after-bundling).
