### ISSUE TITLE
Getting started on JSFiddle is not reactive

### ISSUE THREAD

**Issue by techtonik** [vuejs/vuejs.org#634]
https://vuejs.org/v2/guide/#Getting-Started recommends https://jsfiddle.net/chrisvfritz/50wL7mdz/ as a playground. However, `app` object exists only in frame, and setting `app.message` there has no effect.

**Comment by varbrad** [comment]
````javascript
var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue.js!'
  }
})

app.message = 'hello!'
````

This works perfectly fine for me in jsfiddle, and the Vue instance is indeed reactive. Are you sure you referred to the Vue instance as a var?

**Comment by simplesmiler** [comment]
I think @techtonik meant, that when you run the example and open the devtools, you can't access the `app` variable because it is contained within the iframe.
There's nothing we can do with this, it's a security measure from JSFiddle.

Being able to access `app` from the console applies to when you created an `.html` file with corresponding content, and opened the devtools on that file.

**Comment by omidkrad** [comment]
One workaround could be to add `debugger;` after defining `app`, open devtools, press the run button, and then try `app.message = 'hello!'` in the console window. However, this is not intuitive at all for a beginner, especially when the getting started guide is implying that it should work out of the box.

**Comment by chrisvfritz** [comment]
We're actually having conversations with the incredibly nice people at JSFiddle now about how we can improve our demos. In the not-too-distant future, we might get built-in support for single-file components and an attached console scoped to the demo. 😍
