### ISSUE TITLE
Inaccuracy in comparisons guide about mobx

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [vuejs/vuejs.org#670]
The React + MobX workflow __can't simply__ be thought of as a more verbose Vue.

MobX can observe changes like [array[index] = newValue](https://github.com/mobxjs/mobx/blob/c3d0ce47ef3f86323006c3a0804dba1004193896/src/types/observablearray.ts#L472) and [object.prop = newValue](https://github.com/mobxjs/mobx/blob/c3d0ce47ef3f86323006c3a0804dba1004193896/src/types/observableobject.ts#L125), without using extra method like `this.$set(this.someObject, 'b', 2) `. But apparently there are performance overhead because there are more getter and setter to setup and more dependencies to track.

**Comment by simplesmiler** [comment]
MobX does not support `object.newProp = newValue`: https://mobxjs.github.io/mobx/best/pitfalls.html#-object-somenewprop-value-is-not-picked-up

It supports `array[index] = newValue` up to including the length of the array by making trade offs (copying the original array and wrapping it with an adapter, loosing support for things like `Array.isArray` and changing the semantics of some methods, e.g. `sort`, `reverse`).

**Comment by chrisvfritz** [comment]
@Nick-The-Uncharted We acknowledge in the comparison that it's not that simple:

> __To a limited extent__, the React + MobX workflow can be thought of as a more verbose Vue

The bolding is mine. I appreciate you bringing this up, but I'm not sure details like that are really worth mentioning, simply because I can't imagine it influencing anyone's decision on whether to use Vue or React for a project. Both reactivity systems include annoying, but easy-to-work-around gotchas. I personally prefer Vue's workaround, since it solves the edge case without introducing more, but I could easily live with either.

Do you disagree? Are there aspects you think could significantly sway people one way or the other?

**Comment by Nick-The-Uncharted** [comment]
@chrisvfritz I agree, I was reading source code of MobX and I knew this library by reading vue's doc. It surprise me that it can detect changes in array because vue's doc says that:
> Due to limitations in JavaScript, Vue cannot detect the following changes to an array.

which led me to believe that detecting changes in array is impossible.
