### ISSUE TITLE
manifest.json

### ISSUE THREAD

**Issue by morigs** [vuejs/vuejs.org#769]
I think it's need to add manifest.json for ability to add site to the homescreen. But the question is where to put icons and manifest. And how to modify `_config.yml` :tired_face:

Also I think `#4fc08d` is good for `theme_color`

**Comment by JLHwung** [comment]
> (where to put icons) and manifest

The `manifest.json` can be placed to `src/`.

> where to put icons

The icon is located in `themes/vue/source/images`.

> `And how to modify _config.yml`

It is unnecessary to modify `_config.yml`. If you mean referencing the `manifest.json`, you can revise `themes/vue/layout/layout.ejs`.

**Comment by gogamwar** [comment]
@JLHwung Thanks for reply. I'll try this today and if all is OK send PR

**Comment by gogamwar** [comment]
Omg, I forgot one import thing. This requires https. And Service Workers too (#771).
In my opinion the lack of https on the official website is a real problem.
https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/

**Comment by chrisvfritz** [comment]
@gogamwar Hm, I'm not sure I see what you mean by "not by default". When I try to visit the site without SSL, I'm correctly redirected.

**Comment by gogamwar** [comment]
@chrisvfritz It's really strange. On my Chrome for Android and Firefox on Ubuntu it's correctly redirect me too. But on Chrome on Ubuntu/Windows and Edge when I write ```vuejs.org``` and press enter:
```
Request URL:http://vuejs.org/
Request Method:GET
Status Code:200 OK
Remote Address:104.31.84.3:80
```
I can open site with SSL only by manually typing ```https://...```

**Comment by chrisvfritz** [comment]
That is weird. I believe we're using HSTS for SSL, which [should be supported](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security#Browser_support) by all the browsers you listed. 😕

**Comment by gogamwar** [comment]
Okay, now it's working on Chrome for Ubuntu but still does not work in Edge 38.13393.0.0 and Chrome 56.0.2924.87 for Windows. Maybe the problem is due to the browser but I don't see `Strict-Transport-Security`. :weary:
**Headers from Chrome**
<details> 
  <summary>Response headers</summary>
<pre>HTTP/1.1 200 OK
Date: Sun, 19 Feb 2017 17:03:23 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Last-Modified: Sun, 19 Feb 2017 05:45:40 GMT
Access-Control-Allow-Origin: *
Expires: Sun, 19 Feb 2017 17:13:23 GMT
Cache-Control: max-age=600
Content-Encoding: gzip
X-GitHub-Request-Id: 3F08:1EBAE:722A982:91ED79F:58A9CFDB
X-Content-Type-Options: nosniff
Server: cloudflare-nginx
CF-RAY: 333b4aba155b4f2c-DME</pre>
</details>
<details> 
  <summary>Request headers</summary>
<pre>
GET / HTTP/1.1
Host: vuejs.org
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: __cfduid=...; _gat=1; _ga=...
</pre>
</details>

**Comment by chrisvfritz** [comment]
I've reached out to a few colleagues with more expertise here. Hopefully we'll get a lead soon!
