### ISSUE TITLE
About "compare to react" section, is React reactive?

### ISSUE THREAD

**Issue by CodinCat** [vuejs/vuejs.org#802]
The documentation says 

> both Vue and React provide **reactive** and composable view components

But can we say that React is reactive?

React itself doesn't detect your state changes at all. Unlike Vue, there is no dependency tracking. You must use `setState()` to tell React you have an update. Also React doesn't care about your state, it just re-render anyway, even there is no state changed.

I think React is reactive only if it is combined with something like [MobX](https://mobx.js.org/).

*The quote from react doc*

> *There is an internal joke in the team that React should have been called "Schedule" because React does not want to be fully "reactive".*

**Comment by chrisvfritz** [comment]
I think reactive is one of those words that has different meanings to different people in each community. One might say that `setState` is simply _how_ state is updated and React does track those updates automatically. One could also argue that Vue isn't fully reactive, since it can't track _all_ state changes without similar methods (e.g. `Vue.set`/`Vue.delete`). For the intents and purposes of the comparison, both libraries are _reactive enough_.
