### ISSUE TITLE
The Caveats2 in List Rendering,  example1.items.splice function  can't achive as exprected  in some cases

### ISSUE THREAD

**Issue by sqfbeijing** [vuejs/vuejs.org#963]
```
When you modify the length of the array, e.g. vm.items.length = newLength

To deal with caveat 2, you can also use splice:
example1.items.splice(newLength)
```
 **But when  the newLength Is greater than the current length, this methods failure.
for  example**

<img width="519" alt="qq20170619-095112 2x" src="https://user-images.githubusercontent.com/12571054/27266770-22f753f6-54d6-11e7-8e99-716513f3dbb6.png">

**Comment by sqfbeijing** [comment]
`T T why the code snippet look wrong`

**Comment by chrisvfritz** [comment]
I just update the docs to remove the `also` in `you can also use splice`. Hopefully, this makes it clearer that we recommend `splice` as an _alternative_ to directly setting the length of an array. 

As an aside, I don't actually recommend setting `length` to increase the size of an array in JavaScript. What you get at the end is not actually an array with 8 indices containing the value `undefined`, as it would appear, but rather 8 indices with _undefined pointers_. The difference is subtle, but has important implications. For example, if you try to `map` over this array with `a.map(() => 3)`, what you'll get is `[3, 3, undefined x 8]`, rather than `[3, 3, 3, 3, 3, 3, 3, 3, 3, 3]` as you might expect.
